sonar.projectKey=danielomera59-afk_linkfree
sonar.organization=danielomera59-afk
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/*.test.ts,**/node_modules/**
sonar.tests=backend/src
sonar.test.inclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.coverage.exclusions=frontend/src/**,backend/src/index.ts,backend/src/prisma.ts